export type TeamMember = {
  team: string;
  name: string;
  role: string;
  linkedin: string;
  twitter: string;
  github: string;
};

export const teamMembers = [
  {
    team: "Programs",
    name: "Kate",
    role: "IC",
    linkedin: "https://www.linkedin.com/in/katedo",
    github: "",
    twitter: "",
  },
  {
    team: "Programs",
    name: "Julian",
    role: "",
    linkedin: "https://www.linkedin.com/in/julwrites/",
    github: "",
    twitter: "",
  },
  {
    team: "Programs",
    name: "Joel Loh",
    role: "",
    linkedin: "https://www.linkedin.com/in/joel-loh-2074a6207/",
    github: "",
    twitter: "https://github.com/julwrites",
  },
  {
    team: "Programs",
    name: "Sam",
    role: "",
    linkedin: "",
    github: "",
    twitter: "",
  },
  {
    team: "Programs",
    name: "Elizabeth",
    role: "",
    linkedin: "https://www.linkedin.com/in/elizabeth-hong-ky/",
    github: "",
    twitter: "",
  },
  {
    team: "Programs",
    name: "Xin Hui",
    role: "",
    linkedin: "https://www.linkedin.com/in/xinhui-su-621323210",
    github: "",
    twitter: "https://github.com/tiramisuxh",
  },
  {
    team: "Venue, Logistics & Swag",
    name: "Joel",
    role: "IC",
    linkedin: "https://www.linkedin.com/in/joel-tio/",
    github: "",
    twitter: "https://github.com/joeltio",
  },
  {
    team: "Venue, Logistics & Swag",
    name: "Ethan Chew",
    role: "",
    linkedin: "https://www.linkedin.com/in/ethan-chew/",
    github: "https://github.com/Ethan-Chew",
    twitter: "",
  },
  {
    team: "Venue, Logistics & Swag",
    name: "Gao En",
    role: "",
    linkedin: "",
    github: "",
    twitter: "",
  },
  {
    team: "Venue, Logistics & Swag",
    name: "Daksh",
    role: "",
    linkedin: "https://www.linkedin.com/in/daksh-thapar/",
    github: "",
    twitter: "https://github.com/DakshRocks21 ",
  },
  {
    team: "Registration & PR ",
    name: "Thu Ya",
    role: "IC",
    linkedin: "https://www.linkedin.com/in/thuyakyaw/",
    github: "https://twitter.com/iamthuya",
    twitter: "",
  },
  {
    team: "Registration & PR ",
    name: "Johan",
    role: "",
    linkedin: "",
    github: "",
    twitter: "",
  },
  {
    team: "Registration & PR ",
    name: "Kewei",
    role: "",
    linkedin: "",
    github: "",
    twitter: "",
  },
  {
    team: "Design & Marketing",
    name: "Yeji",
    role: "IC",
    linkedin: "https://www.linkedin.com/in/sungyeji/",
    github: "",
    twitter: "",
  },
  {
    team: "Design & Marketing",
    name: "Yeng",
    role: "",
    linkedin: "https://www.linkedin.com/in/yengrarugal/",
    github: "",
    twitter: "",
  },
  {
    team: "Design & Marketing",
    name: "Estee",
    role: "",
    linkedin: "https://www.linkedin.com/in/estee-tey/",
    github: "https://twitter.com/estee_tey",
    twitter: "https://github.com/lyqht",
  },
  {
    team: "Design & Marketing",
    name: "Shiang Hui",
    role: "",
    linkedin: "https://www.linkedin.com/in/ongshianghui/",
    github: "",
    twitter: "",
  },
  {
    team: "Food & Cleanup",
    name: "Kevin",
    role: "IC",
    linkedin: "https://www.linkedin.com/in/kevin-patrick-tan-95304b104/",
    github: "",
    twitter: "",
  },
  {
    team: "Food & Cleanup",
    name: "James Lim",
    role: "",
    linkedin: "https://www.linkedin.com/in/james-lim-557bb0153/",
    github: "",
    twitter: "",
  },
  {
    team: "Food & Cleanup",
    name: "Pearlyn",
    role: "",
    linkedin: "https://www.linkedin.com/in/pearlyn-pang-8736b061/",
    github: "",
    twitter: "",
  },
  {
    team: "Sponsorship & Judges",
    name: "Roger",
    role: "IC",
    linkedin: "https://www.linkedin.com/in/rogeryeosm/",
    github: "",
    twitter: "https://github.com/rogeryeosgit",
  },
  {
    team: "Sponsorship & Judges",
    name: "Bryan",
    role: "",
    linkedin: "",
    github: "",
    twitter: "",
  },
  {
    team: "Sponsorship & Judges",
    name: "Karpal",
    role: "",
    linkedin: "",
    github: "",
    twitter: "",
  },
];
